### ISSUE TITLE
Don't use the grunt-contrib prefix

### ISSUE THREAD

**Issue by sindresorhus** [i18next/grunt-i18next#2]
The `grunt-contrib` prefix is reserved for officially supported grunt tasks in the [grunt org](https://github.com/gruntjs/).

Please rename this task to not use the `contrib` word both here and on npm.

*(I'm on the [Grunt team](https://github.com/orgs/gruntjs/members))*

**Comment by sabarasaba** [comment]
Now, that took a long a long time. Fixed with: 04844b81384cf25c0a46cd4c59b1d869c90cf50a
