### ISSUE TITLE
Warning: ENOTDIR, not a directory 

### ISSUE THREAD

**Issue by Wilkins** [i18next/grunt-i18next#5]
Hi,

I'm using grunt and i18next in one of my project.
I thought I could use your grunt-i18next plugin.

First of all, your README.md is not very clear, so I'm not sure what your plugin wants to do :-)
So I figured I would install it and see by myself, I have a question at the end, but since I encountered troubles, I'm explaining it all here to help others.

My grunt config :
```node
    i18next: {
      locales:{
        src: ['locales/*/*'],
        dest: 'lang'
      }
    },
```

I first use the grunt-contrib-i18next plugin but I had this error :

```
$ grunt i18next -v
Running "i18next" task

Running "i18next:locales" (i18next) task
Verifying property i18next.locales exists in config...OK
Files: locales, locales/en, locales/en/ns.special.json, locales/fr, locales/fr/ns.special.json, locales/it, locales/it/ns.special.json -> lang
Reading locales/en/ns.special.json...OK
Parsing locales/en/ns.special.json...OK
Reading lang/ns.special.json...OK
Parsing lang/ns.special.json...OK
Warning: Cannot call method 'apply' of undefined Use --force to continue.

Aborted due to warnings.
```

Then, I saw #2, so I changed the plugin to use grunt-i18next with the same config, and then I had :
```
$ grunt i18next -v
Running "i18next" task

Running "i18next:locales" (i18next) task
Verifying property i18next.locales exists in config...OK
Files: locales/en/ns.special.json, locales/fr/ns.special.json, locales/it/ns.special.json -> lang
Warning: ENOTDIR, not a directory 'locales/en/ns.special.json' Use --force to continue.

Aborted due to warnings.
```
So I changed my configuration to :
```node
    i18next: {
      fr:{
        src: ['locales/fr/'],
        dest: 'lang/fr'
      },
      en:{
        src: ['locales/en/'],
        dest: 'lang/en'
      },
      it:{
        src: ['locales/it/'],
        dest: 'lang/it'
      }
    },
```

And now it works fine :

```
$ grunt i18next -v
Running "i18next" task

Running "i18next:fr" (i18next) task
Verifying property i18next.fr exists in config...OK
Files: locales/fr/ -> lang/fr
Reading locales/fr/ns.special.json...OK
Parsing locales/fr/ns.special.json...OK
Reading lang/fr/ns.special.json...OK
Parsing lang/fr/ns.special.json...OK
Writing lang/fr/ns.special.json...OK

Running "i18next:en" (i18next) task
Verifying property i18next.en exists in config...OK
Files: locales/en/ -> lang/en
Reading locales/en/ns.special.json...OK
Parsing locales/en/ns.special.json...OK
Writing lang/en/ns.special.json...OK

Running "i18next:it" (i18next) task
Verifying property i18next.it exists in config...OK
Files: locales/it/ -> lang/it
Reading locales/it/ns.special.json...OK
Parsing locales/it/ns.special.json...OK
Writing lang/it/ns.special.json...OK

Done, without errors.
```

I think I might miss something, because I don't see what this plugin adds more than minify/uglify the json locales files. 
My questions :
- Do I use the locales files correctly ?
- Is this plugin suppose to merge all the locales files for each language but since I have only one by language, it's useless for me ?
- Did I misconfigured something ?

Thank you.

**Comment by MartijnR** [comment]
I think the issue was that locales has to point to a folder and in your first `src: ['locales/*/*'],`, it was pointing to json files. `src: ['locales/*']` maybe would do the trick.

Since this is quite an old issue and you likely moved on, I'm closing this. Just re-open when necessary.
